server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
management:
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/scans
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"                                